//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestante
    {
        public Gestante()
        {
            this.GestanteCita = new HashSet<GestanteCita>();
            this.GestanteMedicamento = new HashSet<GestanteMedicamento>();
            this.GestanteMonitoreo = new HashSet<GestanteMonitoreo>();
        }
    
        public int GestanteKey { get; set; }
        public string GestanteId { get; set; }
        public string Nombres { get; set; }
        public string APaterno { get; set; }
        public string AMaterno { get; set; }
        public Nullable<System.DateTime> FechaUltimaRegla { get; set; }
        public Nullable<System.DateTime> FechaProbableParto { get; set; }
        public Nullable<int> DiagnosticoIngreso { get; set; }
        public Nullable<int> DiagnosticoEgreso { get; set; }
        public int EstablecimientoId { get; set; }
        public string GestanteTelefono { get; set; }
        public string GestanteDireccion { get; set; }
        public string GestanteEmail { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string DistritoId { get; set; }
        public string ProvinciaId { get; set; }
        public string RegionId { get; set; }
        public string GestanteNroDocumento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> DiagnosticoIntermedio1 { get; set; }
        public Nullable<int> DiagnosticoIntermedio2 { get; set; }
        public Nullable<bool> Eliminado { get; set; }
        public int UsuarioEditor { get; set; }
        public byte HorarioMensaje { get; set; }
        public int PresionSistolicaBase { get; set; }
        public int PresionDiastolicaBase { get; set; }
        public int EstablecimientoNotificacionId { get; set; }
    
        public virtual Establecimiento Establecimiento { get; set; }
        public virtual ICollection<GestanteCita> GestanteCita { get; set; }
        public virtual ICollection<GestanteMedicamento> GestanteMedicamento { get; set; }
        public virtual ICollection<GestanteMonitoreo> GestanteMonitoreo { get; set; }
        public virtual Diagnostico DiagEgreso { get; set; }
        public virtual Diagnostico DiagIngreso { get; set; }
        public virtual Diagnostico DiagIntermedio1 { get; set; }
        public virtual Diagnostico DiagIntermedio2 { get; set; }
        public virtual Establecimiento EstablecimientoNotificacion { get; set; }
    }
}
