//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroEvento
    {
        public int RegistroEventoKey { get; set; }
        public int UsuarioKey { get; set; }
        public Nullable<System.DateTime> EventoFecha { get; set; }
        public Nullable<int> IdRegistro { get; set; }
        public string Origen { get; set; }
        public byte IdTipoAccion { get; set; }
        public byte IdTipoObjeto { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual TipoAccion TipoAccion { get; set; }
        public virtual TipoObjeto TipoObjeto { get; set; }
    }
}
