//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TelemonitoreoEntities : DbContext
    {
        public TelemonitoreoEntities()
            : base("name=TelemonitoreoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Establecimiento> Establecimientos { get; set; }
        public virtual DbSet<Gestante> Gestantes { get; set; }
        public virtual DbSet<GestanteCita> GestanteCitas { get; set; }
        public virtual DbSet<GestanteMedicamento> GestanteMedicamentos { get; set; }
        public virtual DbSet<GestanteMonitoreo> GestanteMonitoreos { get; set; }
        public virtual DbSet<Medicamento> Medicamentos { get; set; }
        public virtual DbSet<RegistroEvento> RegistroEventos { get; set; }
        public virtual DbSet<Ubigeo> Ubigeos { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Rol> Roles { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<GestanteMedicamentoDetalle> GestanteMedicamentoDetalle { get; set; }
        public virtual DbSet<Diagnostico> Diagnosticos { get; set; }
        public virtual DbSet<ContenidoMensajeEducacional> ContenidoMensajeEducacional { get; set; }
        public virtual DbSet<MensajeEducacional> MensajeEducacional { get; set; }
        public virtual DbSet<TipoAccion> TipoAccion { get; set; }
        public virtual DbSet<TipoObjeto> TipoObjeto { get; set; }
        public virtual DbSet<SmsQueue> SmsQueues { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sproc_AddUpdateGestante(Nullable<short> pMode, Nullable<int> pGestanteKey, string pGestanteNroDocumento, string pNombres, string pAPaterno, string pAMaterno, Nullable<System.DateTime> pFechaNacimiento, Nullable<System.DateTime> pFechaUltimaRegla, Nullable<System.DateTime> pFechaProbableParto, Nullable<int> pPresionSistolicaBase, Nullable<int> pPresionDiastolicaBase, Nullable<int> diagnosticoIngreso, Nullable<int> pDiagnosticoIntermedio1, Nullable<int> pDiagnosticoIntermedio2, Nullable<int> pDiagnosticoEgreso, Nullable<int> pEstablecimientoId, Nullable<int> pEstablecimientoNotificacionId, string pGestanteTelefono, string pGestanteDireccion, string pGestanteEmail, string pDistritoId, string pProvinciaId, string pRegionId, Nullable<int> pUsuarioEditor, Nullable<byte> pHorarioMensaje)
        {
            var pModeParameter = pMode.HasValue ?
                new ObjectParameter("pMode", pMode) :
                new ObjectParameter("pMode", typeof(short));
    
            var pGestanteKeyParameter = pGestanteKey.HasValue ?
                new ObjectParameter("pGestanteKey", pGestanteKey) :
                new ObjectParameter("pGestanteKey", typeof(int));
    
            var pGestanteNroDocumentoParameter = pGestanteNroDocumento != null ?
                new ObjectParameter("pGestanteNroDocumento", pGestanteNroDocumento) :
                new ObjectParameter("pGestanteNroDocumento", typeof(string));
    
            var pNombresParameter = pNombres != null ?
                new ObjectParameter("pNombres", pNombres) :
                new ObjectParameter("pNombres", typeof(string));
    
            var pAPaternoParameter = pAPaterno != null ?
                new ObjectParameter("pAPaterno", pAPaterno) :
                new ObjectParameter("pAPaterno", typeof(string));
    
            var pAMaternoParameter = pAMaterno != null ?
                new ObjectParameter("pAMaterno", pAMaterno) :
                new ObjectParameter("pAMaterno", typeof(string));
    
            var pFechaNacimientoParameter = pFechaNacimiento.HasValue ?
                new ObjectParameter("pFechaNacimiento", pFechaNacimiento) :
                new ObjectParameter("pFechaNacimiento", typeof(System.DateTime));
    
            var pFechaUltimaReglaParameter = pFechaUltimaRegla.HasValue ?
                new ObjectParameter("pFechaUltimaRegla", pFechaUltimaRegla) :
                new ObjectParameter("pFechaUltimaRegla", typeof(System.DateTime));
    
            var pFechaProbablePartoParameter = pFechaProbableParto.HasValue ?
                new ObjectParameter("pFechaProbableParto", pFechaProbableParto) :
                new ObjectParameter("pFechaProbableParto", typeof(System.DateTime));
    
            var pPresionSistolicaBaseParameter = pPresionSistolicaBase.HasValue ?
                new ObjectParameter("pPresionSistolicaBase", pPresionSistolicaBase) :
                new ObjectParameter("pPresionSistolicaBase", typeof(int));
    
            var pPresionDiastolicaBaseParameter = pPresionDiastolicaBase.HasValue ?
                new ObjectParameter("pPresionDiastolicaBase", pPresionDiastolicaBase) :
                new ObjectParameter("pPresionDiastolicaBase", typeof(int));
    
            var diagnosticoIngresoParameter = diagnosticoIngreso.HasValue ?
                new ObjectParameter("DiagnosticoIngreso", diagnosticoIngreso) :
                new ObjectParameter("DiagnosticoIngreso", typeof(int));
    
            var pDiagnosticoIntermedio1Parameter = pDiagnosticoIntermedio1.HasValue ?
                new ObjectParameter("pDiagnosticoIntermedio1", pDiagnosticoIntermedio1) :
                new ObjectParameter("pDiagnosticoIntermedio1", typeof(int));
    
            var pDiagnosticoIntermedio2Parameter = pDiagnosticoIntermedio2.HasValue ?
                new ObjectParameter("pDiagnosticoIntermedio2", pDiagnosticoIntermedio2) :
                new ObjectParameter("pDiagnosticoIntermedio2", typeof(int));
    
            var pDiagnosticoEgresoParameter = pDiagnosticoEgreso.HasValue ?
                new ObjectParameter("pDiagnosticoEgreso", pDiagnosticoEgreso) :
                new ObjectParameter("pDiagnosticoEgreso", typeof(int));
    
            var pEstablecimientoIdParameter = pEstablecimientoId.HasValue ?
                new ObjectParameter("pEstablecimientoId", pEstablecimientoId) :
                new ObjectParameter("pEstablecimientoId", typeof(int));
    
            var pEstablecimientoNotificacionIdParameter = pEstablecimientoNotificacionId.HasValue ?
                new ObjectParameter("pEstablecimientoNotificacionId", pEstablecimientoNotificacionId) :
                new ObjectParameter("pEstablecimientoNotificacionId", typeof(int));
    
            var pGestanteTelefonoParameter = pGestanteTelefono != null ?
                new ObjectParameter("pGestanteTelefono", pGestanteTelefono) :
                new ObjectParameter("pGestanteTelefono", typeof(string));
    
            var pGestanteDireccionParameter = pGestanteDireccion != null ?
                new ObjectParameter("pGestanteDireccion", pGestanteDireccion) :
                new ObjectParameter("pGestanteDireccion", typeof(string));
    
            var pGestanteEmailParameter = pGestanteEmail != null ?
                new ObjectParameter("pGestanteEmail", pGestanteEmail) :
                new ObjectParameter("pGestanteEmail", typeof(string));
    
            var pDistritoIdParameter = pDistritoId != null ?
                new ObjectParameter("pDistritoId", pDistritoId) :
                new ObjectParameter("pDistritoId", typeof(string));
    
            var pProvinciaIdParameter = pProvinciaId != null ?
                new ObjectParameter("pProvinciaId", pProvinciaId) :
                new ObjectParameter("pProvinciaId", typeof(string));
    
            var pRegionIdParameter = pRegionId != null ?
                new ObjectParameter("pRegionId", pRegionId) :
                new ObjectParameter("pRegionId", typeof(string));
    
            var pUsuarioEditorParameter = pUsuarioEditor.HasValue ?
                new ObjectParameter("pUsuarioEditor", pUsuarioEditor) :
                new ObjectParameter("pUsuarioEditor", typeof(int));
    
            var pHorarioMensajeParameter = pHorarioMensaje.HasValue ?
                new ObjectParameter("pHorarioMensaje", pHorarioMensaje) :
                new ObjectParameter("pHorarioMensaje", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sproc_AddUpdateGestante", pModeParameter, pGestanteKeyParameter, pGestanteNroDocumentoParameter, pNombresParameter, pAPaternoParameter, pAMaternoParameter, pFechaNacimientoParameter, pFechaUltimaReglaParameter, pFechaProbablePartoParameter, pPresionSistolicaBaseParameter, pPresionDiastolicaBaseParameter, diagnosticoIngresoParameter, pDiagnosticoIntermedio1Parameter, pDiagnosticoIntermedio2Parameter, pDiagnosticoEgresoParameter, pEstablecimientoIdParameter, pEstablecimientoNotificacionIdParameter, pGestanteTelefonoParameter, pGestanteDireccionParameter, pGestanteEmailParameter, pDistritoIdParameter, pProvinciaIdParameter, pRegionIdParameter, pUsuarioEditorParameter, pHorarioMensajeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sproc_AddUpdateGestanteMonitoreo(Nullable<int> pGestanteKey, Nullable<int> pPresionSistolica, Nullable<int> pPresionDiastolica, Nullable<int> pProteinuria, Nullable<int> pMovimientosFetales, string pSignosAlarma)
        {
            var pGestanteKeyParameter = pGestanteKey.HasValue ?
                new ObjectParameter("pGestanteKey", pGestanteKey) :
                new ObjectParameter("pGestanteKey", typeof(int));
    
            var pPresionSistolicaParameter = pPresionSistolica.HasValue ?
                new ObjectParameter("pPresionSistolica", pPresionSistolica) :
                new ObjectParameter("pPresionSistolica", typeof(int));
    
            var pPresionDiastolicaParameter = pPresionDiastolica.HasValue ?
                new ObjectParameter("pPresionDiastolica", pPresionDiastolica) :
                new ObjectParameter("pPresionDiastolica", typeof(int));
    
            var pProteinuriaParameter = pProteinuria.HasValue ?
                new ObjectParameter("pProteinuria", pProteinuria) :
                new ObjectParameter("pProteinuria", typeof(int));
    
            var pMovimientosFetalesParameter = pMovimientosFetales.HasValue ?
                new ObjectParameter("pMovimientosFetales", pMovimientosFetales) :
                new ObjectParameter("pMovimientosFetales", typeof(int));
    
            var pSignosAlarmaParameter = pSignosAlarma != null ?
                new ObjectParameter("pSignosAlarma", pSignosAlarma) :
                new ObjectParameter("pSignosAlarma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sproc_AddUpdateGestanteMonitoreo", pGestanteKeyParameter, pPresionSistolicaParameter, pPresionDiastolicaParameter, pProteinuriaParameter, pMovimientosFetalesParameter, pSignosAlarmaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sproc_AddUpdateGestanteCita(Nullable<short> pMode, Nullable<int> pGestanteCitaId, Nullable<int> pGestanteKey, Nullable<System.DateTime> pFechaCita, string pHoraCita, string nombreMedico, Nullable<int> establecimientoId, Nullable<int> pUsuarioEditor)
        {
            var pModeParameter = pMode.HasValue ?
                new ObjectParameter("pMode", pMode) :
                new ObjectParameter("pMode", typeof(short));
    
            var pGestanteCitaIdParameter = pGestanteCitaId.HasValue ?
                new ObjectParameter("pGestanteCitaId", pGestanteCitaId) :
                new ObjectParameter("pGestanteCitaId", typeof(int));
    
            var pGestanteKeyParameter = pGestanteKey.HasValue ?
                new ObjectParameter("pGestanteKey", pGestanteKey) :
                new ObjectParameter("pGestanteKey", typeof(int));
    
            var pFechaCitaParameter = pFechaCita.HasValue ?
                new ObjectParameter("pFechaCita", pFechaCita) :
                new ObjectParameter("pFechaCita", typeof(System.DateTime));
    
            var pHoraCitaParameter = pHoraCita != null ?
                new ObjectParameter("pHoraCita", pHoraCita) :
                new ObjectParameter("pHoraCita", typeof(string));
    
            var nombreMedicoParameter = nombreMedico != null ?
                new ObjectParameter("NombreMedico", nombreMedico) :
                new ObjectParameter("NombreMedico", typeof(string));
    
            var establecimientoIdParameter = establecimientoId.HasValue ?
                new ObjectParameter("EstablecimientoId", establecimientoId) :
                new ObjectParameter("EstablecimientoId", typeof(int));
    
            var pUsuarioEditorParameter = pUsuarioEditor.HasValue ?
                new ObjectParameter("pUsuarioEditor", pUsuarioEditor) :
                new ObjectParameter("pUsuarioEditor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sproc_AddUpdateGestanteCita", pModeParameter, pGestanteCitaIdParameter, pGestanteKeyParameter, pFechaCitaParameter, pHoraCitaParameter, nombreMedicoParameter, establecimientoIdParameter, pUsuarioEditorParameter);
        }
    
        public virtual ObjectResult<sproc_GetAllMenuOptions_Result> sproc_GetAllMenuOptions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_GetAllMenuOptions_Result>("sproc_GetAllMenuOptions");
        }
    
        public virtual ObjectResult<Nullable<int>> sproc_InsertEnviarMensajesEducacionales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sproc_InsertEnviarMensajesEducacionales");
        }
    
        public virtual ObjectResult<Nullable<int>> sproc_InsertRecordatorioMedicamentos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sproc_InsertRecordatorioMedicamentos");
        }
    
        public virtual ObjectResult<Nullable<int>> sproc_InsertRecordatorioCitas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sproc_InsertRecordatorioCitas");
        }
    
        public virtual ObjectResult<sproc_ReportEvolucionGestante_Result> sproc_ReportEvolucionGestante()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_ReportEvolucionGestante_Result>("sproc_ReportEvolucionGestante");
        }
    
        public virtual ObjectResult<sproc_ReportMedicacionGestante_Result> sproc_ReportMedicacionGestante()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_ReportMedicacionGestante_Result>("sproc_ReportMedicacionGestante");
        }
    
        public virtual ObjectResult<sproc_GetEstablecimientos_Result> sproc_GetEstablecimientos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_GetEstablecimientos_Result>("sproc_GetEstablecimientos");
        }
    
        public virtual ObjectResult<sproc_ReportGestantesParticipantes_Result> sproc_ReportGestantesParticipantes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_ReportGestantesParticipantes_Result>("sproc_ReportGestantesParticipantes");
        }
    
        public virtual ObjectResult<sproc_ReportListadoEvolucionGestantes_Result> sproc_ReportListadoEvolucionGestantes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_ReportListadoEvolucionGestantes_Result>("sproc_ReportListadoEvolucionGestantes");
        }
    
        public virtual ObjectResult<sproc_ReportProcedenciaGestantes_Result> sproc_ReportProcedenciaGestantes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_ReportProcedenciaGestantes_Result>("sproc_ReportProcedenciaGestantes");
        }
    
        public virtual ObjectResult<sproc_ReportListadoResumenGestante_Result> sproc_ReportListadoResumenGestante()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sproc_ReportListadoResumenGestante_Result>("sproc_ReportListadoResumenGestante");
        }
    
        public virtual ObjectResult<Nullable<int>> sproc_InsertRecordatorioReporteMonitoreo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sproc_InsertRecordatorioReporteMonitoreo");
        }
    }
}
