//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.RegistroEvento = new HashSet<RegistroEvento>();
            this.MensajeEducacional = new HashSet<MensajeEducacional>();
        }
    
        public int UsuarioKey { get; set; }
        public string Nombres { get; set; }
        public string APaterno { get; set; }
        public string AMaterno { get; set; }
        public int EstablecimientoId { get; set; }
        public string UsuarioDireccion { get; set; }
        public byte EstadoId { get; set; }
        public string Id { get; set; }
        public int UsuarioEditor { get; set; }
        public Nullable<bool> Eliminado { get; set; }
        public byte RecibeAlertas { get; set; }
    
        public virtual Establecimiento Establecimiento { get; set; }
        public virtual ICollection<RegistroEvento> RegistroEvento { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual ICollection<MensajeEducacional> MensajeEducacional { get; set; }
    }
}
