//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContenidoMensajeEducacional
    {
        public int IdContenidoMensajeEducacional { get; set; }
        public int IdMensajeEducacional { get; set; }
        public string Contenido { get; set; }
        public Nullable<System.DateTime> FechaUltimoProceso { get; set; }
        public byte DiaSemana { get; set; }
    
        public virtual MensajeEducacional MensajeEducacional { get; set; }
    }
}
