//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestanteCita
    {
        public int GestanteCitaId { get; set; }
        public int GestanteKey { get; set; }
        public System.DateTime FechaCita { get; set; }
        public string HoraCita { get; set; }
        public string NombreMedico { get; set; }
        public int EstablecimientoId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> Eliminado { get; set; }
        public int UsuarioEditor { get; set; }
    
        public virtual Gestante Gestante { get; set; }
        public virtual Establecimiento Establecimiento { get; set; }
    }
}
