//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestanteMedicamentoDetalle
    {
        public int GestanteMedicamentoDetalleId { get; set; }
        public int GestanteMedicamentoId { get; set; }
        public int MedicamentoId { get; set; }
        public string Dosis { get; set; }
        public Nullable<int> Dias { get; set; }
        public string Cantidad { get; set; }
        public string Instrucciones { get; set; }
        public Nullable<System.DateTime> FechaUltimoProceso { get; set; }
    
        public virtual GestanteMedicamento GestanteMedicamento { get; set; }
        public virtual Medicamento Medicamento { get; set; }
    }
}
