//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamento
    {
        public Medicamento()
        {
            this.GestanteMedicamentoDetalle = new HashSet<GestanteMedicamentoDetalle>();
        }
    
        public int MedicamentoId { get; set; }
        public string Descripcion { get; set; }
        public string Concentracion { get; set; }
        public string Formato { get; set; }
        public string Presentacion { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string NumeroRegistro { get; set; }
        public string Titular { get; set; }
        public Nullable<int> IdDIGEMID { get; set; }
    
        public virtual ICollection<GestanteMedicamentoDetalle> GestanteMedicamentoDetalle { get; set; }
    }
}
