//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsQueue
    {
        public int SmsQueueId { get; set; }
        public string NumeroMovil { get; set; }
        public string TipoMensaje { get; set; }
        public string CuerpoMensaje { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Procesado { get; set; }
        public string ResultadoProceso { get; set; }
        public bool ErrorProceso { get; set; }
        public Nullable<System.DateTime> FechaProceso { get; set; }
    }
}
