//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubigeo
    {
        public int IDUbigeo { get; set; }
        public string CodUbigeo { get; set; }
        public string CodDpto { get; set; }
        public string CodProv { get; set; }
        public string CodDist { get; set; }
        public string Nombre { get; set; }
        public bool EsDpto { get; set; }
        public bool EsProv { get; set; }
        public bool EsDist { get; set; }
    }
}
