//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Telemonitoreo.pe.gob.susalud.app12 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSaludSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TablaGenerica))]
    public partial class ServiceSalud : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetListaEstablecimientoSaludOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListaEstablecimientoSalud_MIDISOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceSalud() {
            this.Url = global::Telemonitoreo.Properties.Settings.Default.Telemonitoreo_pe_gob_susalud_app12_ServiceSalud;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetListaEstablecimientoSaludCompletedEventHandler GetListaEstablecimientoSaludCompleted;
        
        /// <remarks/>
        public event GetListaEstablecimientoSalud_MIDISCompletedEventHandler GetListaEstablecimientoSalud_MIDISCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListaEstablecimientoSalud", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EstablecimientoSalud[] GetListaEstablecimientoSalud(string Ubigeo, string CodDisaRedMicroRed, string CodCentroPoblado, string DescripcionEntidadSectorial, string CodigoSectorial) {
            object[] results = this.Invoke("GetListaEstablecimientoSalud", new object[] {
                        Ubigeo,
                        CodDisaRedMicroRed,
                        CodCentroPoblado,
                        DescripcionEntidadSectorial,
                        CodigoSectorial});
            return ((EstablecimientoSalud[])(results[0]));
        }
        
        /// <remarks/>
        public void GetListaEstablecimientoSaludAsync(string Ubigeo, string CodDisaRedMicroRed, string CodCentroPoblado, string DescripcionEntidadSectorial, string CodigoSectorial) {
            this.GetListaEstablecimientoSaludAsync(Ubigeo, CodDisaRedMicroRed, CodCentroPoblado, DescripcionEntidadSectorial, CodigoSectorial, null);
        }
        
        /// <remarks/>
        public void GetListaEstablecimientoSaludAsync(string Ubigeo, string CodDisaRedMicroRed, string CodCentroPoblado, string DescripcionEntidadSectorial, string CodigoSectorial, object userState) {
            if ((this.GetListaEstablecimientoSaludOperationCompleted == null)) {
                this.GetListaEstablecimientoSaludOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListaEstablecimientoSaludOperationCompleted);
            }
            this.InvokeAsync("GetListaEstablecimientoSalud", new object[] {
                        Ubigeo,
                        CodDisaRedMicroRed,
                        CodCentroPoblado,
                        DescripcionEntidadSectorial,
                        CodigoSectorial}, this.GetListaEstablecimientoSaludOperationCompleted, userState);
        }
        
        private void OnGetListaEstablecimientoSaludOperationCompleted(object arg) {
            if ((this.GetListaEstablecimientoSaludCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListaEstablecimientoSaludCompleted(this, new GetListaEstablecimientoSaludCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListaEstablecimientoSalud_MIDIS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EstablecimientoSalud[] GetListaEstablecimientoSalud_MIDIS(string Ubigeo, string CodDisaRedMicroRed, string CodCentroPoblado, string DescripcionEntidadSectorial, string CodigoSectorial) {
            object[] results = this.Invoke("GetListaEstablecimientoSalud_MIDIS", new object[] {
                        Ubigeo,
                        CodDisaRedMicroRed,
                        CodCentroPoblado,
                        DescripcionEntidadSectorial,
                        CodigoSectorial});
            return ((EstablecimientoSalud[])(results[0]));
        }
        
        /// <remarks/>
        public void GetListaEstablecimientoSalud_MIDISAsync(string Ubigeo, string CodDisaRedMicroRed, string CodCentroPoblado, string DescripcionEntidadSectorial, string CodigoSectorial) {
            this.GetListaEstablecimientoSalud_MIDISAsync(Ubigeo, CodDisaRedMicroRed, CodCentroPoblado, DescripcionEntidadSectorial, CodigoSectorial, null);
        }
        
        /// <remarks/>
        public void GetListaEstablecimientoSalud_MIDISAsync(string Ubigeo, string CodDisaRedMicroRed, string CodCentroPoblado, string DescripcionEntidadSectorial, string CodigoSectorial, object userState) {
            if ((this.GetListaEstablecimientoSalud_MIDISOperationCompleted == null)) {
                this.GetListaEstablecimientoSalud_MIDISOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListaEstablecimientoSalud_MIDISOperationCompleted);
            }
            this.InvokeAsync("GetListaEstablecimientoSalud_MIDIS", new object[] {
                        Ubigeo,
                        CodDisaRedMicroRed,
                        CodCentroPoblado,
                        DescripcionEntidadSectorial,
                        CodigoSectorial}, this.GetListaEstablecimientoSalud_MIDISOperationCompleted, userState);
        }
        
        private void OnGetListaEstablecimientoSalud_MIDISOperationCompleted(object arg) {
            if ((this.GetListaEstablecimientoSalud_MIDISCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListaEstablecimientoSalud_MIDISCompleted(this, new GetListaEstablecimientoSalud_MIDISCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EstablecimientoSalud : TablaGenerica {
        
        private string codigoEstSaludField;
        
        private string tipoEstabDescField;
        
        private string codClasificacionField;
        
        private string descClasificacionField;
        
        private string estabNombreField;
        
        private string estabNombreComerField;
        
        private string institucionField;
        
        private string estabDirField;
        
        private string estUbigeoField;
        
        private string provDescField;
        
        private string depaDescField;
        
        private string distDescField;
        
        private string estTelefonoField;
        
        private string estRadioField;
        
        private string tipoDocFuncionamField;
        
        private string docFuncionamField;
        
        private string estabOtraLicenciaField;
        
        private string estabEmailField;
        
        private string fechaInicioField;
        
        private string fechaCreacionField;
        
        private string estabNroResField;
        
        private string ctgCodigoField;
        
        private string estabTipoDocField;
        
        private string estabDocGzField;
        
        private string estAmbienteField;
        
        private string servFunField;
        
        private string servSuspenField;
        
        private string especialidadField;
        
        private string estabGrupoObjField;
        
        private string estabHorarioField;
        
        private string estabEstadoField;
        
        private string estabSituacionField;
        
        private string estabCondicionField;
        
        private string estabInspeccionField;
        
        private string yField;
        
        private string xField;
        
        private string zField;
        
        private string codCcPpField;
        
        private string descCcPpField;
        
        private string estabCodDisaField;
        
        private string estabCodRedField;
        
        private string estabCodMRedField;
        
        private string estabDescDisaField;
        
        private string estabDescRedField;
        
        private string estabDescMRedField;
        
        private string estabEstrategicoField;
        
        private string estabSectorField;
        
        private string estabRepresentanteField;
        
        private string codDepartamentoField;
        
        private string codProvinciaField;
        
        private string codDistritoField;
        
        private string etiquetaField;
        
        /// <remarks/>
        public string CodigoEstSalud {
            get {
                return this.codigoEstSaludField;
            }
            set {
                this.codigoEstSaludField = value;
            }
        }
        
        /// <remarks/>
        public string TipoEstabDesc {
            get {
                return this.tipoEstabDescField;
            }
            set {
                this.tipoEstabDescField = value;
            }
        }
        
        /// <remarks/>
        public string CodClasificacion {
            get {
                return this.codClasificacionField;
            }
            set {
                this.codClasificacionField = value;
            }
        }
        
        /// <remarks/>
        public string DescClasificacion {
            get {
                return this.descClasificacionField;
            }
            set {
                this.descClasificacionField = value;
            }
        }
        
        /// <remarks/>
        public string EstabNombre {
            get {
                return this.estabNombreField;
            }
            set {
                this.estabNombreField = value;
            }
        }
        
        /// <remarks/>
        public string EstabNombreComer {
            get {
                return this.estabNombreComerField;
            }
            set {
                this.estabNombreComerField = value;
            }
        }
        
        /// <remarks/>
        public string Institucion {
            get {
                return this.institucionField;
            }
            set {
                this.institucionField = value;
            }
        }
        
        /// <remarks/>
        public string EstabDir {
            get {
                return this.estabDirField;
            }
            set {
                this.estabDirField = value;
            }
        }
        
        /// <remarks/>
        public string EstUbigeo {
            get {
                return this.estUbigeoField;
            }
            set {
                this.estUbigeoField = value;
            }
        }
        
        /// <remarks/>
        public string ProvDesc {
            get {
                return this.provDescField;
            }
            set {
                this.provDescField = value;
            }
        }
        
        /// <remarks/>
        public string DepaDesc {
            get {
                return this.depaDescField;
            }
            set {
                this.depaDescField = value;
            }
        }
        
        /// <remarks/>
        public string DistDesc {
            get {
                return this.distDescField;
            }
            set {
                this.distDescField = value;
            }
        }
        
        /// <remarks/>
        public string EstTelefono {
            get {
                return this.estTelefonoField;
            }
            set {
                this.estTelefonoField = value;
            }
        }
        
        /// <remarks/>
        public string EstRadio {
            get {
                return this.estRadioField;
            }
            set {
                this.estRadioField = value;
            }
        }
        
        /// <remarks/>
        public string TipoDocFuncionam {
            get {
                return this.tipoDocFuncionamField;
            }
            set {
                this.tipoDocFuncionamField = value;
            }
        }
        
        /// <remarks/>
        public string DocFuncionam {
            get {
                return this.docFuncionamField;
            }
            set {
                this.docFuncionamField = value;
            }
        }
        
        /// <remarks/>
        public string EstabOtraLicencia {
            get {
                return this.estabOtraLicenciaField;
            }
            set {
                this.estabOtraLicenciaField = value;
            }
        }
        
        /// <remarks/>
        public string EstabEmail {
            get {
                return this.estabEmailField;
            }
            set {
                this.estabEmailField = value;
            }
        }
        
        /// <remarks/>
        public string FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        public string FechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
            }
        }
        
        /// <remarks/>
        public string EstabNroRes {
            get {
                return this.estabNroResField;
            }
            set {
                this.estabNroResField = value;
            }
        }
        
        /// <remarks/>
        public string CtgCodigo {
            get {
                return this.ctgCodigoField;
            }
            set {
                this.ctgCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string EstabTipoDoc {
            get {
                return this.estabTipoDocField;
            }
            set {
                this.estabTipoDocField = value;
            }
        }
        
        /// <remarks/>
        public string EstabDocGz {
            get {
                return this.estabDocGzField;
            }
            set {
                this.estabDocGzField = value;
            }
        }
        
        /// <remarks/>
        public string EstAmbiente {
            get {
                return this.estAmbienteField;
            }
            set {
                this.estAmbienteField = value;
            }
        }
        
        /// <remarks/>
        public string ServFun {
            get {
                return this.servFunField;
            }
            set {
                this.servFunField = value;
            }
        }
        
        /// <remarks/>
        public string ServSuspen {
            get {
                return this.servSuspenField;
            }
            set {
                this.servSuspenField = value;
            }
        }
        
        /// <remarks/>
        public string Especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
            }
        }
        
        /// <remarks/>
        public string EstabGrupoObj {
            get {
                return this.estabGrupoObjField;
            }
            set {
                this.estabGrupoObjField = value;
            }
        }
        
        /// <remarks/>
        public string EstabHorario {
            get {
                return this.estabHorarioField;
            }
            set {
                this.estabHorarioField = value;
            }
        }
        
        /// <remarks/>
        public string EstabEstado {
            get {
                return this.estabEstadoField;
            }
            set {
                this.estabEstadoField = value;
            }
        }
        
        /// <remarks/>
        public string EstabSituacion {
            get {
                return this.estabSituacionField;
            }
            set {
                this.estabSituacionField = value;
            }
        }
        
        /// <remarks/>
        public string EstabCondicion {
            get {
                return this.estabCondicionField;
            }
            set {
                this.estabCondicionField = value;
            }
        }
        
        /// <remarks/>
        public string EstabInspeccion {
            get {
                return this.estabInspeccionField;
            }
            set {
                this.estabInspeccionField = value;
            }
        }
        
        /// <remarks/>
        public string Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        public string X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public string Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        public string CodCcPp {
            get {
                return this.codCcPpField;
            }
            set {
                this.codCcPpField = value;
            }
        }
        
        /// <remarks/>
        public string DescCcPp {
            get {
                return this.descCcPpField;
            }
            set {
                this.descCcPpField = value;
            }
        }
        
        /// <remarks/>
        public string EstabCodDisa {
            get {
                return this.estabCodDisaField;
            }
            set {
                this.estabCodDisaField = value;
            }
        }
        
        /// <remarks/>
        public string EstabCodRed {
            get {
                return this.estabCodRedField;
            }
            set {
                this.estabCodRedField = value;
            }
        }
        
        /// <remarks/>
        public string EstabCodMRed {
            get {
                return this.estabCodMRedField;
            }
            set {
                this.estabCodMRedField = value;
            }
        }
        
        /// <remarks/>
        public string EstabDescDisa {
            get {
                return this.estabDescDisaField;
            }
            set {
                this.estabDescDisaField = value;
            }
        }
        
        /// <remarks/>
        public string EstabDescRed {
            get {
                return this.estabDescRedField;
            }
            set {
                this.estabDescRedField = value;
            }
        }
        
        /// <remarks/>
        public string EstabDescMRed {
            get {
                return this.estabDescMRedField;
            }
            set {
                this.estabDescMRedField = value;
            }
        }
        
        /// <remarks/>
        public string EstabEstrategico {
            get {
                return this.estabEstrategicoField;
            }
            set {
                this.estabEstrategicoField = value;
            }
        }
        
        /// <remarks/>
        public string EstabSector {
            get {
                return this.estabSectorField;
            }
            set {
                this.estabSectorField = value;
            }
        }
        
        /// <remarks/>
        public string EstabRepresentante {
            get {
                return this.estabRepresentanteField;
            }
            set {
                this.estabRepresentanteField = value;
            }
        }
        
        /// <remarks/>
        public string CodDepartamento {
            get {
                return this.codDepartamentoField;
            }
            set {
                this.codDepartamentoField = value;
            }
        }
        
        /// <remarks/>
        public string CodProvincia {
            get {
                return this.codProvinciaField;
            }
            set {
                this.codProvinciaField = value;
            }
        }
        
        /// <remarks/>
        public string CodDistrito {
            get {
                return this.codDistritoField;
            }
            set {
                this.codDistritoField = value;
            }
        }
        
        /// <remarks/>
        public string Etiqueta {
            get {
                return this.etiquetaField;
            }
            set {
                this.etiquetaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EstablecimientoSalud))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TablaGenerica {
        
        private int idTablaField;
        
        private string sidTablaField;
        
        private string descripcionField;
        
        /// <remarks/>
        public int idTabla {
            get {
                return this.idTablaField;
            }
            set {
                this.idTablaField = value;
            }
        }
        
        /// <remarks/>
        public string sidTabla {
            get {
                return this.sidTablaField;
            }
            set {
                this.sidTablaField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetListaEstablecimientoSaludCompletedEventHandler(object sender, GetListaEstablecimientoSaludCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListaEstablecimientoSaludCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListaEstablecimientoSaludCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EstablecimientoSalud[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EstablecimientoSalud[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetListaEstablecimientoSalud_MIDISCompletedEventHandler(object sender, GetListaEstablecimientoSalud_MIDISCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListaEstablecimientoSalud_MIDISCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListaEstablecimientoSalud_MIDISCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EstablecimientoSalud[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EstablecimientoSalud[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591